XSLT/mtsuDCtoMODS.xsl, XSLT/mtsubuchananDCtoMODS.xsl, XSLT/mtsup15838coll7DCtoMODS.xsl, XSLT/mtsurchsDCtoMODS.xsl, XSLT/mtsuschoolsDCtoMODS.xsl, XSLT/mtsushadesDCtoMODS.xsl
This PR updates the recordSource template to correctly process dc:publisher>recordContentSource|note@Intermediate Provider. Additionally, this PR removes an unnecessary mode swith from several collection-level stylesheets.
=> [DPLA-12] modify MTSU transforms for intermediate provider

XSLT/thumbnailsFedoraDCtoMODS.xsl
*JIRA TICKET* - [DPLA-33](https://jira.lib.utk.edu/browse/DPLA-33)
While working on [DLTN Flask](https://github.com/markpbaggett/dltn_flask), my students noticed none of the Crossroads to Freedom thumbnails were loading.  After doing some digging, it became apparent that the domain changed.  This updates the domain name.
See:
* [Fedora response](http://fedora.crossroadstofreedom.org/fedora/get/rds:45372/)
* [Thumbnail example](http://fedora.crossroadstofreedom.org/fedora/get/rds:105679/thumbnail_100x75.jpg)
1. cp current transform on dpla.lib.utk.edu to *.bak. 
2. Mv this transform to the directory remembering that case is different.  
3. Touch all files in directory.
4. Look at the MODS metadata prefix and see if the first few /mods/location/url[@type='object in context'] resolve. …
=> Update Crossroads Fedora DNS.

XSLT/crossroadsDCtoMODS.xsl, XSLT/knoxpublicDCtoMODS.xsl, XSLT/memphisDCtoMODS.xsl, XSLT/nashvilleDCtoMODS.xsl, XSLT/tslaDCtoMODS.xsl, XSLT/utcDCtoMODS.xsl
_Jira tickets:_ [DPLA-22](https://jira.lib.utk.edu/projects/DPLA/issues/DPLA-22), [DPLA-31](https://jira.lib.utk.edu/projects/DPLA/issues/DPLA-31)
1. applies a test to crossroadsDCtoMODS.xsl to avoid processing OAI_DC records that do not have all of the following: at least one dc:title, at least one dc:identifier that starts with an 'http://', and at least one dc:rights element (DPLA-22).
2. updates the github repository URL in /mods/recordInfo/recordOrigin to point to utkdigitalinitiatives.
This is a PR to bring this repository in line with what is currently running on the server. Apologies for the lengthy delay in making these changes available to origin.
@markpbaggett 
@kzayasru
=> fixes for the following tickets: DPLA-22, DPLA-31 

XSLT/mtsuDCtoMODS.xsl
**GitHub Issue: [Issue 8](https://github.com/utkdigitalinitiatives/DLTN/issues/8)**
* Example record missing a [recordInfo/recordContentSource](http://cqa-tn.dp.la:8080/qa/compare?id=fddeb1e73f16ed404703aedfdc4d51a9)
For MTSU records, if no dc:publishers exist, it writes the following to the metadata record:
`<recordInfo><recordContentSource>Digital Initiatives, James E. Walker Library, Middle Tennessee State University</recordContentSource></recordInfo>`
A simple conditional that counts dc:publishers.
* If you have access to a Repox instance, does applying the pull request and touching all existing XSLT …
=> Address Issue #8.

XSLT/memphisDCtoMODS.xsl
**GitHub Issue**: [Issue 11](https://github.com/utkdigitalinitiatives/DLTN/issues/11)
Removes any dc:contributors from Memphis that start with "Description by".
* Added a when statement to the dc:contributor choose to look for things that start with "Description by"
* Note:  I decided there was little to no benefit of this stuff getting mapped to MODS as a marcrelator since it ultimately won't make it in DPLA.
* If you run a full Scema validation on the feed the transform(s) …
=> Address Issue #11.

Sample_Data/UTK/short.volvoices.oai.mods.xml, XSLT/utkMODStoMODS.xsl
**GitHub Issue: [Issue 20](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/20)
This PR addresses some malformed XML in utkMODStoMODS.xsl, as well as correcting the sequence of children elements in the new mods:location element.
Updated apply-templates in the new mods:location element at line 32, and added specific template match rules for the children elements.
Using oXygen, apply the new utkMODStoMODS to the truncated example in Sample_Data/UTK/. Review the output.
@markpbaggett
=> Issue 20 fix location template

Sample_Data/UTK/short.volvoices.oai.mods.xml, XSLT/utkMODStoMODS.xsl
**GitHub Issue: [Issue 19 - recordContentSource](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/19)
Introduces granularity in how we're handling the UTK recordInfo element and its children. Specifically addresses the possibility of empty recordContentSource elements.
This PR adds child-level templates to the recordInfo rule, specifically to address potentially empty recordContentSource elements. XPath predicates are used to test for a child text() node in recordContentSource -- if there is one, there is a normal copy-of applied.
Acquire my branch, and run the utkMODStoMODS.xsl against the Sample_Data/UTK/short.volvoices.oai.mods.xml. 
There is a commented out empty recordContentSource that can be used to verify proper behavior from the predicate tests.
@markpbaggett
=> Issue 19 recordContentSource

Sample_Data/Country/records/musicaudio_2073.xml, Sample_Data/Country/records/musicaudio_2074.xml, Sample_Data/Country/records/musicaudio_4577.xml, Sample_Data/Country/records/musicaudio_5149.xml, XSLT/countryqdctomods.xsl
**JIRA Issue: [DPLA-47](https://jira.lib.utk.edu/browse/DPLA-47)
This PR adds a QDC-to-MODS XSL transform, as well as sample data files, for Country Music Hall of Fame.
The following files have been added to the repository:
```
|--Sample_Data
|--Country
|--countryqdc.xml
|--records
|--musicaudio_2073.xml
|--musicaudio_2074.xml
|--musicaudio_4577.xml
|--musicaudio_5149.xml
|--XSLT
|--countryqdctomods.xsl
```
The `countryqdctomods` stylesheet converts the files under Sample_Data/Country/records to valid MODS. 
* Acquire my branch and open the new stylesheet in oXygen.
* Configure a transform scenario and be sure to use Saxon 8.7!
* Run the transformation scenario
* There are **recoverable** errors reported by Saxon 8.7. These do **not** effect the output of the transform.
* After applying …
=> address DPLA-47

XSLT/coreDCtoMODS.xsl, XSLT/countryqdctomods.xsl, XSLT/crossroadsDCtoMODS.xsl, XSLT/knoxp265301coll005DCtoMODS.xsl, XSLT/knoxp265301coll7DCtoMODS.xsl, XSLT/knoxp265301coll8DCtoMODS.xsl, XSLT/memphisp13039coll5DCtoMODS.xsl, XSLT/mtsuDCtoMODS.xsl, XSLT/mtsucannonDCtoMODS.xsl, XSLT/mtsumtsu1DCtoMODS.xsl, XSLT/mtsup15838coll4DCtoMODS.xsl, XSLT/mtsup15838coll7DCtoMODS.xsl, XSLT/mtsuschoolsDCtoMODS.xsl, XSLT/mtsushadesDCtoMODS.xsl, XSLT/nashvilleDCtoMODS.xsl, XSLT/nashvillenrDCtoMODS.xsl, XSLT/tslaDCtoMODS.xsl, XSLT/utcDCtoMODS.xsl
**GitHub Issue: [DPLA-74](https://jira.lib.utk.edu/projects/DPLA/issues/DPLA-74) | [DLTN-41](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/41)
This PR adds two pieces of functionality:
1) it adds rightsstatements.org parsing to output  `mods:accessCondition` and appropriate attributes, and
2) it adds templating that attempts to force multiple `dc:rights` elements to one `mods:accessCondition` element.
1) Parameters and variables in coreDCtoMODS that allow for rightsstatements.org parsing and `dc:rights` processing accordingly.
2) Updated `dc:rights` template for said processing.
3) Updated `mods:accessCondition` serialization to reflect rightsstatements.org URIs and statements.
4) Updated `mods:accessCondition` serialization to differentiate between local rights statements …
=> Address DPLA-74 DLTN-41

XSLT/countryqdctomods.xsl
**GitHub Issue: n/a
This PR attempts to clean up some weird formatting in two function definitions.
The whitespace in the function definitions has been cleaned up, hopefully improving the legibility of the code. Functionally, there's no difference.
@markpbaggett
=> fix weird wrapping in functions

Sample_Data/UTC/utc.qdc.xml, XSLT/utcqdctomods.xsl
**GitHub Issue: [DPLA-115](https://jira.lib.utk.edu/projects/DPLA/issues/DPLA-115)
This PR adds a QDC->MODS stylesheet for UTC.
* A new transform: utcqdctomods.xsl
This change should *not* impact any other transforms - it has no includes/dependencies on our other stylesheets.
The following would be a good place to start with testing this stylesheet.
* Does the transform validate in Oxygen using th Saxon 8.7 processor?
* Using sample XML code, does the pull request doe what is intended?
* an …
=> Address DPLA-115

XSLT/utkMODStoMODS.xsl
**GitHub Issue: [Issue 58](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/58)
Rewrites the current UTK transform.
* Transform is rewritten so only exceptions are included.
* Check for a roleTerm and convert to creator or contributor.
* Move /accessCondition[@type="local"] to abstract with custom text.
* Using sample XML code, does the pull request do what is intended
* an accessCondition
=> Rewrite UTK XSL transform.

XSLT/tslaqdctomods.xsl
**GitHub Issue**: [GitHub 60](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/60)
Adds a template for TSLA QDC to MODS for their patterns for standardized rights.
TSLA is submitting standardized rights to us in a way where we need to change how rights are handled.  This attempts to do that.
* …
=> Add template to address standardized rights.

XSLT/utkmodstomods.xsl
**GitHub Issue: n/a
Updates template rules for originInfo, physicalDescription, and role processing.
added:
1) positional predicates to form and role
2) predicates to ignore/filter originInfo elements appropriately.
Run vs Sample_Data/UTK/volvoices and verify output is correct.
@markpbaggett
=> originInfo, role, and form fixes

XSLT/utkmodstomods.xsl
**JIRA Issue: [DPLA-197](https://jira.lib.utk.edu/browse/DPLA-197)**
From UTK, if there is a titleInfo node and it is followed or preceded by a titleInfo[@supplied] node, drop it.
Just this one liner transform
* an accessCondition
If we have metadata with 3 titleInfos, it's possible this might not work. …
=> Address DPLA-197. :pouting_cat:

XSLT/utkmodstomods.xsl
**GitHub Issue: N/A
Adds templating to add (or ignore) `location/url[@access]` elements. Adds additional templating to ignore misspelled `identifer` elements (if present).
This should only impact the UTK mods-to-mods stylesheet. 
This should be run with Saxon 8.7 against sample UTK MODS. 
@markpbaggett
=> Correctly address context and preview urls

XSLT/thumbnailscontentdmdctomods.xsl
**GitHub Issue**: [DLTN_XSLT-94](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/94)
**Jira Ticket**: [DPLA-218](https://jira.lib.utk.edu/browse/DPLA-218)
This checks dc:identifier and only maps a preview URL if it contains contentdm and starts with http.
An additional conditional is passed to the function so it's looking for contentdm and http.
Use p15838coll7 and its transform and check the output of *Southern Horrors: Lynch Law in All Its Phases*.  It should only get 1 preview and the right one.
This assumes all contentdm urls contain that phrase.  I'm not 100% sure that's the case.
@mlhale7
=> Address DPLA-218.

Sample_Data/Crossroads/memphis_world.xml
**GitHub Issue**: [DLTN_XSLT-103](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/103)
* [OAI](http://dlynx.rhodes.edu:8080/oai/request?verb=ListRecords&metadataPrefix=xoai&set=col_10267_31334)
* [Digital Collection](http://dlynx.rhodes.edu/jspui/handle/10267/31334)
* [Mapping](https://dltn-technical-docs.readthedocs.io/en/latest/mappings/crossroads.html#col-10267-31334-memphis-world)
Adds a metadata record to test the Memphis World set before going to Repox.
A test record.
1. **REVIEW, APPROVE, AND MERGE [PR-102](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/pull/102)**.
2. Use the rhodes_dspaces_xoai_to_mods.xsl transform.  Since this P.R. hasn't been reviewed and the file is not yet tracked upstream, I kept updating the same transform to keep things easier for us …
=> Add memphis world test.

Sample_Data/Crossroads/oral_histories.xml, XSLT/rhodes_dspace_xoai_to_mods.xsl
**GitHub Issue**: [DLTN_XSLT-111](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/111)
* [Metadata mapping](https://dltn-technical-docs.readthedocs.io/en/latest/mappings/crossroads.html#col-10267-30936-crossroads-to-freedom-oral-history-collection)
This pull requests adds a sample record for Rhodes Oral Histories and makes modifications to the default template that work for both Friends and Family and Oral Histories.
* A sample record to test against
* Adds a namespace for local things to keep things simple
* Adds a list of acceptable params for typeOfResource and a matching incoming value
* Changes the thumbnail xpath selector so that only one thumbnail is ever selected
* Creates a default rule for mapping descriptions to abstract.  This will need to be enhanced later.
* …
=> Add sample record & transform changes for Rhodes Oral Histories.

Sample_Data/Crossroads/maps.xml, XSLT/rhodes_dspace_xoai_to_mods.xsl
**GitHub Issue**: [DLTN_XSLT-113](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/113)
* [Metadata Mapping](https://dltn-technical-docs.readthedocs.io/en/latest/mappings/crossroads.html#col-10267-31149-historic-memphis-maps)
Adds sample data and makes a few changes to the default transform for Historic Maps from Rhodes.
* An example OAI-PMH response for the collection has been added
* A new type value has been added to the $pTypes  param
* A dateOther template has been added to keep things valid when a record has neither a dateIssued nor a publisher.  This value is not mapped to DPLA.
* Run the updated transform against the sample data.
* Are things still valid?
* Are things in line with the metadata mapping.
@mlhale7
=> Address DLTN_XSLT-113.

Sample_Data/State_Library/qdc/Strickland.xml, XSLT/tslaqdctomods.xsl, XSLT/utcqdctomods.xsl
* [DLTN_XSLT-120](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/120)
* [DLTN_XSLT-123](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/123)
* [DLTN_XSLT-125](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/125)
This makes the dc:language templates actually work.
The old templates were not working.  This was due to namespace collision.  They should work with this pull request.
For TSLA, take the updated record and run against the updated transform.
For UTC, use whatever sample qdc utc record you want against its updated transform.
@mlhale7
=> Addess local namepace issues for UTC and TSLA.

XSLT/utcqdctomods.xsl
**GitHub Issue**: [DLTN_XSLT-131](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/131)
* [Mapping](https://dltn-technical-docs.readthedocs.io/en/latest/mappings/utc.html)
Updates the broken link in recordOrigin for UTC.
Just this one line in the main template.
Look at this.  Is it sufficient?  I chose not to directly link to the mapping since it's easy to find from the main page and it's possible the mapping may move within the technical docs.
@mlhale7
=> Update link to UTC metadata mapping.

.gitignore, .travis.yml, README.md, tests/testSchemas/DLTN_oai_mods.xsd, tests/validate_scenarios.sh
**GitHub Issue**: [DLTN_XSLT-141](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/141)
This should get us a framework for utilizing travis for testing.
1. a .gitignore so we don't accidentally commit something associated with the Travis working directory
2. a testSchema/DLTN_oai_mods.xsd file so we can use xmllint for validation
3. a tests/validate_scenarios.sh to store our unit tests
Does our build pass (does the most recent commit have a green check mark)?  If so, check out tests/validate_scenarios.sh and the unit tests.  This means that the 2 defined tests are passing.  We probably should get rid of the java one, but as you can see in our 2nd test:
1. We're taking our newly installed version of saxon-8.7 and running Sample_Data/sternberg.xml  against …
=> Address DLTN_XSLT-141:  Setup initial framework for testing stylesheets and samples.

XSLT/rhodes_dspace_xoai_to_mods.xsl, XSLT/rhodes_dspace_xoai_to_mods_farnsworth.xsl, XSLT/rhodes_sternberg_xoai_to_mods.xsl
**GitHub Issue**: [DLTN_XSLT-154](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/154)
All Rhodes / Crossroads sets are failing in ingestion3 because ingestion3 expects their to be a usage="primary display" value. This adds it.
A simple string upda0te to all 3 Rhodes transforms.
1. Does Travis pass build? If so, this should mean all the transforms result in a valid document.
Code for this is [here](https://github.com/dpla/ingestion3/blob/2b98f6f2ac661ef0cea3129e7a92ab50f82bfcc9/src/main/scala/dpla/ingestion3/mappers/providers/TnMapping.scala#L226)
@mlhale7
=> Address DLTN_XSLT-154: Add usage=primary display for isShownAts.

XSLT/utkmodstomods.xsl, tests/test_data/utk_mods.txt, tests/validate_scenarios.sh
**GitHub Issue**: [DLTN_XSLT-160](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/160)
This adds baseline things to start unit testing data from UTK before passing things to DPLA.
1. A baseline unit test has been added for UTK.  This works similar to how TSLA's works.  Right now, not all sets are there because of how many problems currently exist with the UTK data.
2. A text file for utk sets.  Eventually, we can think about how to programmatically populate this (pyrepox?)
3. A change to utkmodstomods.xsl so that it can mostly be valid.
1. Look at the unit test. Do you understand it?
2. Does Travis pass?
Again, this is just a start.  This data is awful and this unblocks being able to address those problems one by one.
=> Address DLTN_XSLT-160:  initialize unit tests for UTK MODS.

XSLT/rhodes_dspace_xoai_to_mods_farnsworth.xsl, XSLT/rhodes_sternberg_xoai_to_mods.xsl
**GitHub Issue**: [DLTN_XSLT-152](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/152)
Replaces the bad thumbnails for some Rhodes sets.
Instead of copying over the thumbnail link, 2 transforms test for a known bad string and replaces them.
1. Look at Travis output.  Does it pass?
2. Run check and harvest vs. these sets with this transform.  Are there any bad URLs?
I haven't ran Travis stuff yet. Also, I haven't ran check and harvest.  Once travis is done, I'll do that, but it's probably good if someone else checks this as well.
=> Address DLTN_XSLT-152.

XSLT/utkmodstomods.xsl, tests/test_data/utk_mods.txt
**GitHub Issue**: [DLTN_XSLT-163](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/163)
Make unit tests work for UTK sets that need to create a thumbnail from a mods:identifier.
1. Add the affected sets so that automated testing now occurs.
2. Follow @CanOfBees advice on how to address the template by using following-sibling instead of following.
1. Does Travis pass build?
2. Look at the change to the transform.  Do you understand it?
=> Address DLTN_XSLT-163.

XSLT/countryqdctomods.xsl, tests/validate_scenarios.sh
**GitHub Issue**: [DLTN_XSLT-168](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/168)
**GitHub Issue**: [DLTN_XSLT-170](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/170)
Makes Country Music Hall of Fame QDC rights more dynamic.
CMHF is adding a new set.  Not all the records have rights.  This looks for rights in to locations (dcterms:accessRights, dc:rights), and then blankets a rights statement if none exists.
1. Check that Travis passes.
=> Make countryqdc rights more dynamic.

XSLT/countryqdctomods.xsl
**GitHub Issue**: [DLTN_XSLT-175](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/175)
Makes sure we don't end up with an  empty physicalDescription node.
The current cmhfqdc transform expects a form.  Because of this we can have physicalDescriptions with no child nodes and fail validity checking.
1. Look at the transform change.  Does it look good?
2. Did the Travis build pass?
=> Address DLTN_XSLT-175.

XSLT/tslaqdctomods.xsl
**GitHub Issue**: [DLTN_XSLT-174](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/174)
This looks at whether known strings are contained in metadata rather than exact matches.
The current transform looks for specific strings.  This changes things so it only looks for whether a not a string is contained within the test before matching.  I assume that TSLA only has 2 rights statements currently.  If not, they'd always go to local.
1. Look at the transform.  Does it make sense?
2. Does the build pass?
=> Address DLTN_XSLT-174.

XSLT/utkmodstomods.xsl
**GitHub Issue**: [DLTN_XSLT-178](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/178)
Maps dateIssueds and publishers from UTK to our MODS output.
This changes the rules for originInfo.  Now, we map dateIssued to dateCreated and map publisher.  We also only drop originInfo ifthere are no dateCreateds, dateIssueds, or publishers.
1. Read the code.  Does this make sense?
2. Does Travis pass?
=> Address DLTN_XSLT-178.

XSLT/utkmodstomods.xsl
**GitHub Issue**: [DLTN_XSLT-190](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/190)
* [TN Mapper Title Override Method](https://github.com/dpla/ingestion3/blob/develop/src/main/scala/dpla/ingestion3/mappers/providers/TnMapping.scala#L184)
This pull request maps all supplied titles to a regular title so that they don't appear as bad records for DPLA.
Collections like Dabney are not getting into DPLA because they have supplied titles that are not mapped to a title field in MAP 4 and thus appear as a bad record.  This maps those titles to the xpath DPLA expects.
=> Address DLTN_XSLT-190.

tests/test_data/tsla_qdc.txt, tests/test_data/utc_qdc.txt
**GitHub Issue**: [TSLA September Harvest #192](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/192)
Adds a set from TSLA (tsla_p15138coll28) and from UTC (utc_p16877coll32)that were recently added to Repox.
Two new sets.
Make sure the naming of the set matches the set in Repox.
See if Travis passes.
@markpbaggett
=> Add coll28 (TSLA) and coll32 (UTC) to the testing list.

XSLT/countryqdctomods.xsl
**GitHub Issue**: [DLTN_XSLT-204](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/204)
Tokenizes subjects from CMHF correctly.
CMHF does not end all of its concatenated dc:subjects with semi-colons.  For this reason, the subject topic templates do not work as intended.  This fixes that. 
1. Check output of Travis.  Does it pass.
2. Look at a test record from CMHF.  If it's a string of subjects and it doesn't have a trailing semicolon, does it still tokenize?  If so, this works.
@mlhale7
=> Address DLTN_XSLT-204.

tests/test_data/tsla_qdc.txt, tests/test_data/utk_mods.txt
**GitHub Issue**: [211](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/211)
Adds sets being ingested to DPLA for the first time in December 2019. These sets are utk_agrtfn and utk_marchingband. utk_arrow previously existed in set list but was kept empty in Repox due to names  in the data that had spacing and other formatting issues. tsla_p15138coll23 was also slightly renamed after reingesting the set with new data.
utk_agrtfn, utk_marchingband, tsla_p15138coll23
- Do the added set names match the names as entered in Repox?
@CanOfBees
=> Add new sets or updated sets for December ingest.

XSLT/utkmodstomods.xsl
When we added voloh for the March ingest, I failed to recognize that we had new role terms present in the metadata. This pull request adds the new role terms so that the creators and contributors will be present in the DPLA interface.
This pull request adds three new roles (1 creator and 2 contributor roles): "Interviewee", "Interviewer", and "Witness". These are all new role terms present in voloh.
* Take a record from voloh [attached](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/files/4350843/voloh13.txt)
and see if all the names values are included in the resulting MODS.
Keeping the roles up to date in the future would be easier if the creator / contributor values were listed alphabetically by each type. For the purposes of easily seeing the changes, I have not done any …
=> Add new contributor and creator roles

XSLT/utkmodstomods.xsl
This pull request lists creator and contributor roleTerms alphabetically to make it easier to scan them for missing terms in the future. I also fixed a typo in genre ("trasnparencies" to "transparencies")
* Run the transform with sample XML to make sure the code still works after the simple cosmetic changes.
@markpbaggett
=> List roleTerms alphabetically and fix typo.

XSLT/tslaqdctomods.xsl, XSLT/utcqdctomods.xsl
**GitHub Issue**: [228](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/228)
**Jira Issue**: [DPLA-250](https://jirautk.atlassian.net/browse/DPLA-250)
This PR updates utcqdctomods.xsl and tslaqdctomods.xsl so that the correct form of the IIIF link is inserted for records that have a manifest.
Run the updated transforms against sample XML files and see if the correct URL is present in the MODS files.
While Knox Public, Memphis Public, and Nashville Public also have catalog files (indicating that they have IIIF links), I'm not seeing any XSLT files that generate the IIIF URLs. Please comment on how IIIF links were generated for those institutions and let me know if we need to address them in this PR or a separate one. …
=> Change url to manifest.json version for XSLT files.

.travis.yml, tests/validate_scenarios.sh
**GitHub Issue**: [DLTN-232](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/232)
Makes tests with Travis work again.
A few weeks ago, Travis started failing all of a sudden.  I mistakenly blamed this on Travis, but on closer inspection that's not the case.  When Travis would make a request to our installation of Repox, it would respond with a 000 HTTP status code.  While this can be caused by a variety of things, in our case it's based on the SSL library in the Repox jar.  Repox uses an SSL library that is very strict on its interpretation of how SSL should be implemented.  This has caused issues for others before (Vermont), but has never been a problem for us. A few weeks ago, some things happened with SSL and while I'm not clear on all of this, I wouldn't be surprised if …
=> Whats wrong with travis

XSLT/coredctomods.xsl
**GitHub Issue**: [247](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/247)
This PR fixes a rightsstatements URI in the coredctomods transform. A "s" was missing for the URI associated with "No Copyright - United States" and this was causing several records from MTSU's p15838coll7 to be rejected by DPLA. With the added "s", these records should be valid.
Transform sample records from p15838coll7 to MODS and see if the resulting URI for records previously throwing errors is "http://rightsstatements.org/vocab/NoC-US/1.0/". Here are a few test records in DC -
[p15838coll7TestRecords.txt](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/files/5631698/p15838coll7TestRecords.txt)
=> Add "s" to URL.

Sample_Data/TSU/TSUSample_DigCollYearbooksCatalogues.xml, XSLT/tsudctomods.xsl
**GitHub Issue**: [254](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/254)
OAI endpoint - [https://digitalscholarship.tnstate.edu/do/oai/](https://digitalscholarship.tnstate.edu/do/oai/)
This PR adds a transform for Tennessee State University's publication:library-digital-collections, publication:yearbooks, and publication:allcatalogues sets. It also adds a small selection of sample data for all three sets in one XML file. 
Check to make sure that all required fields for DPLA are considered in the transform (title, recordContentSource, accessCondition, thumbnail URL, and object URL). Use the sample data to test transform and ensure that values are represented appropriately (no …
=> Tsu transform

XSLT/knoxcountydctomods_newsets.xsl, XSLT/knoxp16311coll3dctomods.xsl
**GitHub Issue**: [March Ingest sets for Knox County Public Library #260 ](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/260)
**Jira Issue**: [DPLA-255](https://jirautk.atlassian.net/browse/DPLA-255)
Other Relevant Links (OAI Feeds, DPLA Records, Metadata Mappings, DLTN Documentation, Etc.) -  
- [p16311coll3](http://cdm16311.contentdm.oclc.org/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=p16311coll3)
- [p265301coll8](http://cdm16311.contentdm.oclc.org/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=p265301coll8)
- [p15136coll3](http://cdm16311.contentdm.oclc.org/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=p15136coll3)
- [p15136coll4](http://cdm16311.contentdm.oclc.org/oai/oai.php?verb=ListRecords&metadataPrefix=oai_dc&set=p15136coll4)
This PR …
=> Knox transform march2021

tests/test_data/tsla_qdc.txt, tests/test_data/utk_mods.txt
**GitHub Issue**: [258](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/258)
Adds names of two sets (one from UTK, one from TSLA) for testing purposes.
Does the naming of the sets match the naming in Repox? (Don't think Travis still functions?)
When testing for sets was initially set up, we only took UTC, TSLA, and UTK into account. Let me know if we should consider expansion. Note that all new sets have been tested with check and harvest.
=> Add two sets for testing purposes for March 2021 DPLA ingest.

XSLT/mtsup15838coll16dctomods.xsl
**Jira Issue**: [DPLA-262](https://jirautk.atlassian.net/browse/DPLA-262)
OAI link for set - http://cdm15838.contentdm.oclc.org/oai/oai.php?verb=ListRecords&set=p15838coll16&metadataPrefix=oai_dc
This transform converts MTSU's oai_dc for a set to MODS. The set, p15838coll16, is the first collection from MTSU to be added since 2017. Apologies for not opening this sooner, but I was waiting for MTSU to fix some rights values on their end (this collection actually has all rightsstatements!).
Check to make sure resulting records include all required DPLA fields (title, object link, thumbnail link, provider, rights). Here's 
[some sample records](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/fi …
=> Create transform for MTSU Clothing Collection.

XSLT/christianbrothersuniversitydctomods.xsl
CBU OAI-PMH: [https://cdm15916.contentdm.oclc.org/oai/oai.php](http://cdm15916.contentdm.oclc.org/oai/oai.php)
CBU wants to reingest in December and they have taken the time to implement rights statements in their metadata. Instead of blanket writing in "Copyright Not Evaluated", I wanted to briefly rework the transform to match what they've assigned on their end. I can include all the rightsstatements, but this currently just has three.
Test the transform with sample data from CBU's endpoint. Also comment if changes need to be made to make this transform less brittle.
@markpbaggett @CanOfBees
=> Adding potential for specific rights statement to be included.

tests/test_data/tsla_qdc.txt, tests/test_data/utk_mods.txt
**GitHub Issue**: [273](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/273)
Adds new sets for testing that will be ingested on Dec. 20th.
These sets for UTK and TSLA:
- utk_ladysoft
- utk_ladytrack
- utk_ladyvolley
- utk_mengolf
- utk_mentennis
- utk_wrestling
- utk_ladysoccer
- utk_ladyswim
- utk_ladyrowing
- utk_rfta
- tsla_p15138coll49
- tsla_p15138coll50
- tsla_p15138coll51
Do the set names match what is present in Repox?
@markpbaggett
=> New sets for December ingest

XSLT/montgomerycountyarchivesdctomods.xsl
**GitHub Issue**: [#277](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/277)
MCA's OAI Endpoint - https://cdm17128.contentdm.oclc.org/oai/oai.php
Adds XSLT for Montgomery County Archives. They are adding four sets.
Use the following sample XML file to see if the transform functions as expected. Make sure that required DPLA values (title, link to object, link to thumbnail, rights, provider) are in the MODS that is generated.
[mca_Test.txt](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/files/8288420/mca_Test.txt)
I had a little difficulty making the selection for dc:type not drop some values. It works currently, but I've hard coded in "photographs" and "Photographs" as this …
=> Montgomery county archives

XSLT/chattpubdctermstomods.xsl
**GitHub Issue**: [302](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/302)
**Other Relevant Links**
Chattanooga Public OAI - https://collections.chattlibrary.org/oai
This PR edits the existing transform for Chattanooga Public Library so that the collection title is included.  Jessica Sedgwick wanted this metadata included as it provides important context.
The transform works with dcterms:isPartOf and puts the values into mods:relatedItem
Does this transform do what is intended (include the collection title in MODS)?
The December ingest will be taking place on Dec. 18th. I'm planning to apply this by then.
=> Edit transform to include archival collection in output.

tests/test_data/utc_qdc.txt, tests/test_data/utk_mods.txt
**GitHub Issue**: [306](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/306)
Adds sets for testing added during the December 2023 DPLA ingest.
Adds:
- utc_p16877coll53
- utc_p16877coll52
- utc_p16877coll55
- utk_lanecol
- utk_wallace
Removes:
- utk_revwar
Are all the new and removed sets accounted for? Is the spelling compared to Repox correct?
=> Add sets for testing.

XSLT/montgomerycountyarchivesdctomods.xsl
Associated GitHub Issues: [Issue 310](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/310) 
Relevant Links (OAI Feeds, DPLA Records, Metadata Mappings, DLTN Documentation, Etc.)
*MCA OAI-PMH - https://cdm17128.contentdm.oclc.org/oai/oai.php
This PR adds handling to deal with new form terms present in Montgomery County Archives' metadata for the June 2024 DPLA ingest. 
Use the [mcatestdata.txt](https://github.com/user-attachments/files/15570087/mcatestdata.txt) in Oxygen (change extension to .xml) with the edited transform to see if the form terms and typeOfResource values show up correctly.
@mkaljns - I'm putting you on this PR as I don't know who else to include. The changes are pretty minimal. I'll add you to the DLTN organization so you can have access to the code? I …
=> Add handling for additional form terms for new sets.
