.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Adds a template for new issues, a template for pull requests, and a file to describe how to contribute.
3 new files:
* PULL_REQUEST_TEMPLATE.md -- a starter template for future pull requests.
* CONTRIBUTION.md --a starter file for how to contribute.
* ISSUE_TEMPLATE.md -- a starter template for new issues.
Not necessary.  Just markdown files.
Issues won't likely be a thing until we move to the repo to TennShare.
@CanOfBees
=> Add Contribution files.

XSLT/mtsuDCtoMODS.xsl
**GitHub Issue: [Issue 14](https://github.com/utkdigitalinitiatives/DLTN/issues/14)
Fixes duplicated recordContentSource values in mods:recordInfo in two records in p15838-coll7.
Updated the `test` from `starts-with()` to `contains(normalize-space(.), ...)` to avoid extraneous whitespace in the dc:publisher's text().
* If you run a full Scema validation on the feed the transform(s) applies …
=> Address issue 14

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md
This p.r. affects 2 files:
First:
1. It removes that extra heading and expands the issue template somewhat.  
2. It adds a little information to Contributing.md about issues in general.
Let me know if there are questions before this can be merged.
=> Remove extra heading and update contributing.md.

Sample_Data/State_Library/qdc/Fisk.xml, Sample_Data/State_Library/qdc/Mustard.xml, Sample_Data/State_Library/qdc/Strickland.xml, Sample_Data/State_Library/qdc/mckenneyHal.xml, Sample_Data/State_Library/qdc/p15138coll27.xml
**GitHub Issue**: None
Adds sample QDC records from TSLA.
=> Add sample records from TSLA QDC.

tslaqdctomods.xsl
From our working meeting!
**GitHub Issue: n/a
Adds our initial TSLA QDC -> MODS stylesheet.
@markpbaggett @mlhale7
=> Create tslaqdctomods stylesheet

XSLT/utkMODStoMODS.xsl
**GitHub Issue:** [DLTN-60](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/60)
Fixes some major problems introduced in my last pull request.
Fixes some bad syntax and logic with 2 transforms.
* an accessCondition
This is on server and looks like it's working properly.
=> Address major bugs in current transform.

XSLT/utkmodstomods.xsl
**JIRA Issue: [VVMC-109](https://jira.lib.utk.edu/browse/VVMC-109?jql=labels%20%3D%20septermber18dpla)**
Switches note[@displayLabel="instrumentation"] to abstract.
Added transform to switch note[@displayLabel="instrumentation"] to abstract.
Did I spell it correctly?
I didn't look to see if the displayLabel was spelled correctly in the ticket.
=> Address VVMC-109.

XSLT/utkmodstomods.xsl
Adds a location url if an identifier starts with HTTPS!!!!
@mlhale7
=> Switch http to https. :pouting_cat:

XSLT/catalogs/knoxpub_catalog.xml
=> Add last second fix.

Sample_Data/Crossroads/friends_and_family.xml, Sample_Data/Crossroads/random_friends_and_family.xml, XSLT/rhodes_dspace_xoai_to_mods.xsl
**GitHub Issue**: [DLTN_XSLT-101](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/101)
Adds required things for the Friends and Family set to be added to DPLA.
* Added an xoai to MODS transform that can be used for this set but hopefully others as well.
* an accessCondition
The name of the …
=> Write metadata things for Crossroads Friends and Family.

Sample_Data/Crossroads/beale_street.xml, Sample_Data/Crossroads/everett_cook.xml, Sample_Data/Crossroads/lemoyne.xml, Sample_Data/Crossroads/sanitation.xml, Sample_Data/Crossroads/sugarmon.xml, XSLT/rhodes_dspace_xoai_to_mods.xsl
* [DLTN_XSLT-116](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/116)
* [DLTN_XSLT-114](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/114)
* [DLTN_XSLT-115](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/115)
* [DLTN_XSLT-112](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/112)
* [DLTN_XSLT-110](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/110)
* [Metadata Mapping](https://dltn-technical-docs.readthedocs.io/en/latest/mappings/crossroads.html#mapping-tables)
Finalizes the XSL transform and adds all remaining test data.
* The transform has been modified to not assume rights (some Sanitation Strike tapes have rights) and allow for multiple xpaths to typeOfResource.
* Sample records have been added for all remaining …
=> Crossroads final xoai

CONTRIBUTING.md, README.md, repox_config/metadataSchemas.xml
This adds the current list of allowed metadata schemas in our instance of Repox and updated links to technical docs.
* a metadataSchemas.xml file with all currently allowed metadataSchemas in our Repox instance.
* updates to README with current links to technical docs.
* updates to CONTRIBUTING with instructions for following the XSL style guide.
Just look at it. Is this okay for now?  Do the updates cause more problems than they answer.
@mlhale7
=> Add updated tech docs links and repox config things.

tests/test_data/tsla_qdc.txt, tests/test_data/utk_mods.txt
Adds sets from TSLA and UTK so that unit tests are ran against their data.
That's it.
1. Does build pass?  If so, it's good.
There are other sets for June 2019 that will needed to be added once they are in Repox.
=> Add sets for June 2019 testing.

tests/test_data/utk_mods.txt
Adds three UTK sets newly added to Repox to the sets to be tested.
Check to make sure the sets are present in Repox and are spelled correctly. Check Travis to see if it passes.
@markpbaggett
=> Add three new UTK sets to test data.

tests/test_data/utk_mods.txt
This adds the dabney metadata to the test sets.
Does the set name match the one in repox?
Does Travis pass?
@markpbaggett
=> Add dabney to the test sets.

XSLT/countryqdctomods.xsl
**GitHub Issue**: [DLTN_XSLT-204](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/204)
The previous pull request didn't take into account a trailing semicolon in dc:subject.  This fixes that.
@mlhale7
=> Add logic incase trailing semicolon actually exists.

XSLT/rhodes_dspace_xoai_to_mods.xsl, XSLT/rhodes_dspace_xoai_to_mods_farnsworth.xsl, XSLT/rhodes_sternberg_xoai_to_mods.xsl
**GitHub Issue**: [DLTN_XSLT-207](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/207)
Addresses DLTN_XSLT-207.
1. Does Travis pass?
2. Are the new values acceptable?
@mlhale7
=> Change recordOrigin value.

.travis.yml
**GitHub Issue**: [DLTN_XSLT-217](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/217)
Adds a source to a copy of Saxon 8.7.
Our old saxon 8.7 source is gone so all tests were failing. This should fix it.
Ensure all tests pass.
@CanOfBees
=> Change source for saxon8.7.

tests/test_data/tsla_qdc.txt, tests/test_data/utc_qdc.txt, tests/test_data/utk_mods.txt
**GitHub Issue**: [219](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/219)
This PR adds the new sets for the March DPLA ingest to the lists of test sets.
* Make sure that the added set name matches the set name in Repox.
* Does Travis pass?
@markpbaggett
=> Add new sets for March ingest.

tests/test_data/utk_mods.txt
**GitHub Issue**: [#263](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/263)
Adds utk_tennvolsmag to the sets to be tested.
Is the set in Repox with the same name? Do tests pass?
@markpbaggett
=> Add utk_tennvolsmag to sets to be tested.

tests/test_data/tsla_qdc.txt, tests/test_data/utc_qdc.txt, tests/test_data/utk_mods.txt
**GitHub Issue**: [283](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/283)
Adds new sets for testing purposes associated with the December 2022 DPLA ingest.
- Ensure that the sets match the set name in Repox
=> Add new sets for testing.

XSLT/mtsucoll17dctomods.xsl
**GitHub Issue**: [316](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/316)
* OAI for MTSU for this set: https://cdm15838.contentdm.oclc.org/oai/oai.php?verb=ListRecords&set=p15838coll17&metadataPrefix=oai_dc
This adds a transform to change MTSU's DC data to MODS to be contributed to DPLA for the December 2024 ingest.
Use the sample test data to see if the transform works (
[MTSU_Places_Perspectives_Test.txt](https://github.com/user-attachments/files/18203460/MTSU_Places_Perspectives_Test.txt)). Note that you'll need to change the extension to .xml
See if the resulting XML is valid and that each record includes the following five fields:
- title
- rights
- provider …
=> Add transform for "Places, Perspectives."

XSLT/mtsucoll17dctomods.xsl
**GitHub Issue**: [316](https://github.com/DigitalLibraryofTennessee/DLTN_XSLT/issues/316)
Michael Della Bitta shared that 19 records came back with two rights statements. While existing QA checks to ensure that all records have rights statements, we don't have testing to ensure that there aren't multiple statements that conflict. Here are the problem records:
1.	https://cdm15838.contentdm.oclc.org/digital/collection/p15838coll17/id/574
2.	https://cdm15838.contentdm.oclc.org/digital/collection/p15838coll17/id/335
3.	https://cdm15838.contentdm.oclc.org/digital/collection/p15838coll17/id/337
4.	https://cdm15838.contentdm.oclc.org/digital/collection/p15838coll17/id/336
5.	https://cdm15838.contentdm.oclc.org/digital/collection/p15838coll17/id/369
6. …
=> Fix copypasta errors . . .
